set(LZMA_LIBRARY_NAME "lzma")

# Defines the source code for the library.
set(LZMALIB_SRCS
	${CMAKE_CURRENT_SOURCE_DIR}/7zAlloc.c
	${CMAKE_CURRENT_SOURCE_DIR}/7zAlloc.h
	${CMAKE_CURRENT_SOURCE_DIR}/7zArcIn.c
	${CMAKE_CURRENT_SOURCE_DIR}/7zBuf2.c
	${CMAKE_CURRENT_SOURCE_DIR}/7zBuf.c
	${CMAKE_CURRENT_SOURCE_DIR}/7zBuf.h
	${CMAKE_CURRENT_SOURCE_DIR}/7zCrc.c
	${CMAKE_CURRENT_SOURCE_DIR}/7zCrc.h
	${CMAKE_CURRENT_SOURCE_DIR}/7zCrcOpt.c
	${CMAKE_CURRENT_SOURCE_DIR}/7zDec.c
	${CMAKE_CURRENT_SOURCE_DIR}/7zFile.c
	${CMAKE_CURRENT_SOURCE_DIR}/7zFile.h
	${CMAKE_CURRENT_SOURCE_DIR}/7z.h
	${CMAKE_CURRENT_SOURCE_DIR}/7zStream.c
	${CMAKE_CURRENT_SOURCE_DIR}/7zTypes.h
	${CMAKE_CURRENT_SOURCE_DIR}/7zVersion.h
	${CMAKE_CURRENT_SOURCE_DIR}/7zWindows.h
	${CMAKE_CURRENT_SOURCE_DIR}/Aes.c
	${CMAKE_CURRENT_SOURCE_DIR}/Aes.h
	${CMAKE_CURRENT_SOURCE_DIR}/AesOpt.c
	${CMAKE_CURRENT_SOURCE_DIR}/Alloc.c
	${CMAKE_CURRENT_SOURCE_DIR}/Alloc.h
	${CMAKE_CURRENT_SOURCE_DIR}/Bcj2.c
	${CMAKE_CURRENT_SOURCE_DIR}/Bcj2Enc.c
	${CMAKE_CURRENT_SOURCE_DIR}/Bcj2.h
	${CMAKE_CURRENT_SOURCE_DIR}/Bra86.c
	${CMAKE_CURRENT_SOURCE_DIR}/Bra.c
	${CMAKE_CURRENT_SOURCE_DIR}/Bra.h
	${CMAKE_CURRENT_SOURCE_DIR}/BraIA64.c
	${CMAKE_CURRENT_SOURCE_DIR}/Compiler.h
	${CMAKE_CURRENT_SOURCE_DIR}/CpuArch.c
	${CMAKE_CURRENT_SOURCE_DIR}/CpuArch.h
	${CMAKE_CURRENT_SOURCE_DIR}/Delta.c
	${CMAKE_CURRENT_SOURCE_DIR}/Delta.h
	${CMAKE_CURRENT_SOURCE_DIR}/DllSecur.c
	${CMAKE_CURRENT_SOURCE_DIR}/DllSecur.h
	${CMAKE_CURRENT_SOURCE_DIR}/LzFind.c
	${CMAKE_CURRENT_SOURCE_DIR}/LzFind.h
	${CMAKE_CURRENT_SOURCE_DIR}/LzFindMt.c
	${CMAKE_CURRENT_SOURCE_DIR}/LzFindMt.h
	${CMAKE_CURRENT_SOURCE_DIR}/LzFindOpt.c
	${CMAKE_CURRENT_SOURCE_DIR}/LzHash.h
	${CMAKE_CURRENT_SOURCE_DIR}/Lzma2Dec.c
	${CMAKE_CURRENT_SOURCE_DIR}/Lzma2Dec.h
	${CMAKE_CURRENT_SOURCE_DIR}/Lzma2DecMt.c
	${CMAKE_CURRENT_SOURCE_DIR}/Lzma2DecMt.h
	${CMAKE_CURRENT_SOURCE_DIR}/Lzma2Enc.c
	${CMAKE_CURRENT_SOURCE_DIR}/Lzma2Enc.h
	${CMAKE_CURRENT_SOURCE_DIR}/Lzma86Dec.c
	${CMAKE_CURRENT_SOURCE_DIR}/Lzma86Enc.c
	${CMAKE_CURRENT_SOURCE_DIR}/Lzma86.h
	${CMAKE_CURRENT_SOURCE_DIR}/LzmaDec.c
	${CMAKE_CURRENT_SOURCE_DIR}/LzmaDec.h
	${CMAKE_CURRENT_SOURCE_DIR}/LzmaEnc.c
	${CMAKE_CURRENT_SOURCE_DIR}/LzmaEnc.h
	${CMAKE_CURRENT_SOURCE_DIR}/LzmaLib.c
	${CMAKE_CURRENT_SOURCE_DIR}/LzmaLib.h
	${CMAKE_CURRENT_SOURCE_DIR}/MtCoder.c
	${CMAKE_CURRENT_SOURCE_DIR}/MtCoder.h
	${CMAKE_CURRENT_SOURCE_DIR}/MtDec.c
	${CMAKE_CURRENT_SOURCE_DIR}/MtDec.h
	${CMAKE_CURRENT_SOURCE_DIR}/Ppmd7.c
	${CMAKE_CURRENT_SOURCE_DIR}/Ppmd7Dec.c
	${CMAKE_CURRENT_SOURCE_DIR}/Ppmd7Enc.c
	${CMAKE_CURRENT_SOURCE_DIR}/Ppmd7.h
	${CMAKE_CURRENT_SOURCE_DIR}/Ppmd.h
	${CMAKE_CURRENT_SOURCE_DIR}/Precomp.h
	${CMAKE_CURRENT_SOURCE_DIR}/RotateDefs.h
	${CMAKE_CURRENT_SOURCE_DIR}/Sha256.c
	${CMAKE_CURRENT_SOURCE_DIR}/Sha256.h
	${CMAKE_CURRENT_SOURCE_DIR}/Sha256Opt.c
	${CMAKE_CURRENT_SOURCE_DIR}/Sort.c
	${CMAKE_CURRENT_SOURCE_DIR}/Sort.h
	${CMAKE_CURRENT_SOURCE_DIR}/SwapBytes.c
	${CMAKE_CURRENT_SOURCE_DIR}/SwapBytes.h
	${CMAKE_CURRENT_SOURCE_DIR}/Threads.c
	${CMAKE_CURRENT_SOURCE_DIR}/Threads.h
	${CMAKE_CURRENT_SOURCE_DIR}/Xz.c
	${CMAKE_CURRENT_SOURCE_DIR}/XzCrc64.c
	${CMAKE_CURRENT_SOURCE_DIR}/XzCrc64.h
	${CMAKE_CURRENT_SOURCE_DIR}/XzCrc64Opt.c
	${CMAKE_CURRENT_SOURCE_DIR}/XzDec.c
	${CMAKE_CURRENT_SOURCE_DIR}/XzEnc.c
	${CMAKE_CURRENT_SOURCE_DIR}/XzEnc.h
	${CMAKE_CURRENT_SOURCE_DIR}/Xz.h
	${CMAKE_CURRENT_SOURCE_DIR}/XzIn.c
)

if (WIN32)
	set(LZMALIB_THREAD_SRCS
		${CMAKE_CURRENT_SOURCE_DIR}/LzFindMt.c
		${CMAKE_CURRENT_SOURCE_DIR}/LzFindMt.h
		${CMAKE_CURRENT_SOURCE_DIR}/Threads.c
		${CMAKE_CURRENT_SOURCE_DIR}/Threads.h
	)
else()
	set(LZMALIB_THREAD_SRCS)
endif()

# Build the library as an object.
set(LZMA_OBJECT_NAME ${LZMA_LIBRARY_NAME}-obj)
set(LZMA_OBJECT_NAME ${LZMA_OBJECT_NAME} PARENT_SCOPE)
add_library(${LZMA_OBJECT_NAME} OBJECT ${LZMALIB_SRCS} ${LZMALIB_THREAD_SRCS})
set_property(TARGET ${LZMA_OBJECT_NAME} PROPERTY POSITION_INDEPENDENT_CODE 1)
